---
title             : "The title"
shorttitle        : "Title"

author: 
  - name          : "First Author"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Conceptualization
      - Writing - Original Draft Preparation
      - Writing - Review & Editing
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2"
    role:
      - Writing - Review & Editing

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  
  One or two sentences to put the results into a more **general context**.
  
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
r_refs("r-references.bib")
```


# Introduction

The development of online education has been evolving over the past few decades, offering an alternative to delivering learning in a more convenient manner to individuals.
<!--- we might consider (not rn but to be discussed) deleted the "could not be physically present" part, it could open a can of worms---> 
Of particular interest is the research and development of online language education along with technological advances that made possible an evolution in the quality and accessibility of the materials. 
For example, implementing online tools such as Zoom, VoiceThread, FlipGrid, etc, allowed students to hold conversations, share ideas and provide their opinions in a similar way to a traditional online setting. 

According to the [@nationalstatistics_2022], during the fall of 2020 over 75 percent of undergraduate students (11.8 million) were enrolled in at least one online course, whereas 44 percent (7.0 million) of all undergraduate students exclusively enrolled in online courses [@nationalstatistics_2022]. 
Compared to Fall 2019, these numbers represent a 97 percent increase in undergraduates taking at least one online course (11.8 million vs. 6.0 million) and a 186 percent increase in undergraduate students enrolled exclusively in online courses (7.0 million vs. 2.4 million).

<!--- I think the above sentence might be unnecessary bc we don't necessarily talk about communicative strategies --> 
<!--- IAR Two lines convined --> 
<!--- for example, x, y, z helps students to do a, b, and c. then start with the next sentence--->  
 Even though many programs already had online versions of their courses,   the Covid-19 pandemic postulated a challenge to many educators, as they were not prepared and, in some cases, lacked of experience teaching the online modality  @tomasik2021educational <!--- in what way? are we saying covid was a challenge for online learning? this seems to go against the previous sentences saying that techology had advanced and online learning has developed-->



<!--- This was a global phenomenon in the history of language education which had many educational consequences that students most likely will continue to experience when approaching online education. - maybe delete this ---> 
With a global decrease in Covid-19 cases, most US universities are slowly beginning to switch to a pre-pandemic educational setting or blend hybrid classes. <!--- idk if we can say "global decrease" maybe something like "with a push to return to pre-covid practices" ---> 
The goal of this paper is twofold, first to identify attitudes towards online language education it in a context where online education is no longer mandatory and, second to better understand how our new post-pandemic reality modulates tendencies in university language class enrollment.

\newpage



# Previous literature and theoretical framework

<!--- i don't know if this paragraph is necessary "Education mirrors society and its challenges, with Covid-19 as a global example of the adaptations that educators around the world had to implement in order to continue providing education to their students. 
In this sense, education can be understood as a continuum that has endlessly developed according to the socioeconomic changes that society experiences throughout history."  -esto quizas entraria mejor como primera linea en "the current study"- --->

The goal of the current paper is to gather information from our current students who are in an educational environment that has been in continuous change for the past few years. 
The effects of this ever-changing learning environment have affected students and continue to affect the way they interact with and view their education. 
Post-pandemic effects, along with world socio-economic changes such as inflation and the need to work, have brought a new educational reality that affects tendencies toward language enrollment. 

<!-- i think this is what needs to be worked on, if you have something in the introcution that fits in any of these categories, add it below and we can work it into a few paragraph to motivate the study ---> 

## Online learning

In several decades of existence and development, online learning has never gained more attention than it did over the national pandemic, as 75 percent of undergraduate students were enrolled in at least one online course [@nationalstatistics_2022].
Previous pre-pandemic research has proven that distance students can archive similar learning goals as those students that were physically present on the educational environment [eg: @mccutcheon2015systematic, @means2013effectiveness, @sun2016online].
While online learning comes with a set of challenges that are not found in a traditional classroom, such as the ability to self-regulate, and the lack of interaction, it can improve the effectiveness and efficiency of education as it eliminates geographical barriers, improving accessibility, and the ability to learn at the student's pace [@kebritchi2017issues]. 

During the pandemic, one of the most cited difficulties with the quick transition to online education was the lack of preparation and families with educational tools.
Being forced to switch moralities had consequences, both from the teachers’ and students’ perspectives, as they were either not ready for the change or lacked many materials.
[@mahyoob2020challenges] describes how both students and educators found technical problems concerning the use of technology, affecting the adequate distribution of teaching materials and communications among the students.
These difficulties faded as the teaching force became more familiar with the learning tools. 
In addition, the stress levels of undergraduates diminished from the beginning to the end of the academic term as they became more familiar with the instructional materials and therefore gained more experience with their newfound educational setting. 
[@ruiz2022transitioning]
Likewise, the attitudes toward the online setting evolved throughout the pandemic. Increased autonomy and self-paced learning opportunities offered by the new online format were overall the most liked attributes of the change. 


#### Effectiveness and attitudes toward online education 
#Intro online learning history

Language attitudes are essential in the language learning environment, as they play an important role in determining the student's final success in the language course.
Similarly, a learner with a positive attitude toward a learning environment will more likely succeed than a learner who finds the environment difficult or disengaged.[eg @thompson2021attitudes] <!--- lets avoid statements that are very direct and assertive like that, something more like "they play a role in determining the success of a student --->
Not surprisingly, the attitudes in online learning have been shown to play a fundamental role as students are physically detached from the learning environment, and rely more on self-regulation abilities [@alqurashi2016self; @horvat2015student; @ke2013constructs; @lan2010using]. 
Within this line of research <!---i'm not sure that framework is the right word here-->, anxiety has been linked in several research studies [e.g.,@teimouri2019second] as an indicator of poor linguistic development. 
<!--- i think this sentence should be deleted "Interestingly, anxiety and the fear of the unknown is a feeling that fluctuates with empirical contact throughout the academic appointment." -como quieras, lo que queria era expresar la idea que a traves de la experiencia y ver el sistema, los niveles de ansiedad disminuyen - -->

@tophatfall2020 did a major survey on undergraduate students’ and teachers’ perceptions at the beginning of the online emergency switch in US universities. 
Their findings within students taking a language class were that overall, the quality of instruction received was worse in comparison to the in-person learning setting. 
In the same way, a vast majority of students felt that the class experience was unengaging as they missed spending time with faculty and fellow students. 
Within this swift change to online settings, many students also found that their academic load was not only reduced but also experienced problems with using online tools.<!--- conexion con como progresivamente la situacion fue mejorando. 


<!--- i'm going to think about how to rework these examples into a paragraph that flows a little better 

Furthermore, @webb2014flipping studied the attitudes of students and teachers in a flipped online classroom of Chinese. 
Their results showed an incremental fluctuation in their perception. 
That is, they found distance education would not meet student expectations at first, but through the semester they found a growing acceptance that led to successful results by the end of a 15-week term. 
A similar psychological development is observed in @ushida2005role study which investigated the changes in students’ attitudes and motivation over time in online language courses. 
Their results showed a similar evolution within the student’s attitudes, as students reduced their anxiety level as the semester progressed, feeling more comfortable with the system as well as the teaching materials by the end of the educational term. 
Past educational experiences and abilities acquired through these experiences have an effect on how students shape attitudes toward a new learning encounter (Saito et al. 2018), as well as the familiarity and complexity of the instruments that the course requires (@heckel2019pride), which might involve some training and assistance before the beginning of the online course. 
During the covid outbreak, students and educators lacked experience with online tools as well as time to prepare, @tomasik2021educational, leading to an overall feeling of less effective education Top hat (2020), @hodges2020difference, @lee2022factors. 
While the immediate transition to online education seemed rushed in @ruiz2022transitioning the stress levels of undergraduates diminished from the beginning to the end of the academic term as they became more familiar with the instructional materials, and therefore gained more experience with their newfound educational setting. 
Their study of US undergraduates found varied responses in which some students enjoyed the increased autonomy and self-paced learning opportunities offered by the new online format. 
Along the same line, a survey of university students found a common belief that online education helped them continue their education while still learning, observing, and improving the quality of teaching as their professors gained more experience with the teaching instruments [@chakraborty2021opinion]. ---> 




#### Motivation


With the decrease in covid cases, most major US universities are looking to transition into face-to-face settings, creating a new reality within language education. 
A global survey [@widenhorn2023comparing] of more than 5.000 university students revealed that more than four in five students (82%) would still want to have at least some of their courses online after having passed two years of the global pandemic. 
Similarly, two in five university students (41%) would still prefer to continue online without physical interaction with the educational classroom. 
When asked what factors other than the pandemic had an impact, students replied with the economy (73%), location or transportation (44%), and lack of access to technology (35%)
This is the most extensive study that tackles the shift toward face-to-face education after the online pandemic to date. 
However, this study is broad as it covers several countries with different economic needs and transportation necessities. 
Therefore, our study aims to provide more fine-grained detail about the post-pandemic tendencies in a North Eastern US university ....

## Grounded theory

In order to study and understand tendencies in online learning, we turned to Grounded Theory, as it allows for a cyclical observation of a changing world, where the researcher is a constant observer of the changes produced [@hernandez2014investigacion]. 
This theoretical approach allows the research team to explain the relationships among categories within the same reality. 
It is a constant comparison methodology of data of the reality being studied, where the hypothesis are formulated throughout the research process. 
This was performed via student evaluations, which allowed to test the thematic coding structuration and check for unanticipated topics. 
In this step, the most noteworthy categories were selected (axial coding) with the intention of making a posterior analysis (selected coding). 
A Qualtrics Survey followed this initial observation, which allowed us to employ a mixed models questionnaire that included qualitative, quantitative, and open-ended questions aimed at gaining information about the participant's experience, attitudes, and motivations for taking online vs. in-person language classes. 
We then tested each category in... (add statisct analysis used). 

Due to the geographical limitations, we adopt a substantive Grounded Theory that helps explain the tendencies seen within a specific area, along with the factors that affect them [@corbin2014basics].
Thus we understand that the results we obtain might be limited to the area from where the information is being extracted.  
Social factors such as distance from campus, commuting time, working hours, or access to the internet might be geographically dependent and not extrapolable to other areas or countries. 


# Current Study

<!--- i think this is "too personal" we should change it to something like, "the current study aims to explore attitudes towards online instruction at an R1 instution in a post-pandemic reality where learning has been adapted to an online learning environment" o algo asi ...
Our premise in this research study is to gather information from our current students who are in an educational environment that has been in continuous change for the past few years. 
The effects of this ever-changing learning environment have affected students and continue to affect modulating the way they interact with and view their education. Post-pandemic effects, along with world socio-economic changes, have brought a new educational reality that affects tendencies toward enrollment. 
Having a better understanding of the constant change of tendencies that affect our students can help us not only in providing them with adequate tools to succeed but also help us in providing courses that match their needs and expectations. ---> 

# Methods

## RQs

The current study aims to answer the following research questions: 

- How effective are online classes according to self-reported measures of language abilities?

- How does our new post-pandemic reality modulate tendencies in language enrollment (in person vs online)?

We predict X based on Y. 

In order to answer the research questions, a total of X students completed an anonymous survey. The following is a description of the participants that took part in the study and the task that they completed. 

## Participants

Students who were taking in person and online Spanish language classes at a Big 10 northeastern university were asked to complete the survey. 
A total number of 87 people responded (update this with final count from Qualtrics). 
The data from 6 surveys were removed due to incomplete responses. 
The participants were compensated with extra credit towards their homework grades in their Spanish courses for completing the survey. 
They were all typical university aged students (ages from 18-25) except one student, who belongs to the 25-35 age range. 
[I don't know if this will be relevant, probably not, but we could include: 35 of the students were first years, 27 were second years, 11 were third years, and 9 were fourth years.] 
Of the # participants who completed the survey, 23 were taking a fully asynchronous online Spanish class, 51 were taking an in person class, and 7 were taking a hybrid course.

We also collected information about their linguistic backgrounds. 
Of the # of participants, 37 of the students speak another language besides English and Spanish. 
The participants reported learning Spanish between the ages of X and X. 
They had reported learning Spanish in X setting. 
X number of participants had taken X number of years of Spanish in a high school setting. 
X students have never taken Spanish courses prior to this course. (look up this information in the survey)

Additionally, we collected information about their work and commuting lives of these participants to be able to make judgements about how these factors impact learning attitudes. 
The students ranged from living on campus (32 students) to living relatively close to campus 5-15 miles away (17 students), to living 15+ miles away from campus and having a long commute (33 students). 
As for their working schedules, 51 students reported to not be currently working while attending university while 31 students are currently studying and working at the same time. 
Of those 31 students who are working, five work between zero and five hours a week, ten work between five to ten hours a week, ten work between ten to fifteen hours and week and six work more than fifteen hours a week.

## Material and Procedure

The survey was created on Qualtrics. 
It was distributed via an online anonymous link to undergraduate students taking Spanish courses in a large university located in the northeast United States and it took an average of # minutes to complete (find this info on qualtrics). 
In total, the participants answered 46 questions. 
The questions were divided into 4 sections (background information, online learning tools/accessibility, attitudes, and enrollment) that each aimed to gather information about different factors that might impact the responses. 
The background information section asked questions about their age, how long they have studied Spanish, how far they live away from campus, and if they are working. 
The online learning tools/accessibility questions asked how comfortable they felt using the learning management systems that their courses are using and how readily accessible stable Wifi, a computer or tablet, and the software and other technologies are that are required for the courses that they are taking. 
The attitudes section aimed to gather the participants' thoughts about learning languages in person and in online settings, their motivations for taking a language course, and how they feel their language abilities have progressed. 
The last section, enrollment, asked questions about school-work balance and the reasons why they enroll in online courses.

The aforementioned sections of the survey followed a mixed-methods design to examine students’ perspectives through an interaction of quantitative and qualitative questions.
By using open-ended and close-ended questionnaires we were able to collect, contrast and students’ testimonies. 
The mixed-methods design of this study allowed us to compare open-ended questions, with close-ended questions obtaining tendencies, preferences, as well as attitudes toward enrollment. 
Close-ended quantitative questions were presented in a scale from 5 to 1 in the questionnaire, with a 5 being valued as “very useful” and a 1 as “not very useful”.

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion

- Tie to RQs and big picture


# Conclusion

- Big Picture

- Limitations

- Future directions

The results of this research study can help inform the decisions that administrations at similar universities make about the courses that they offer in the future. 


\newpage

# References

::: {#refs custom-style="Bibliography"}
:::
